src/Entity/Lists.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ListsRepository")
 */
class Lists
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Users", inversedBy="lists")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author_id;

    /**
     * @ORM\Column(type="boolean")
     */
    private $partage;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getAuthorId(): ?Users
    {
        return $this->author_id;
    }

    public function setAuthorId(?Users $author_id): self
    {
        $this->author_id = $author_id;

        return $this;
    }

    public function getPartage(): ?bool
    {
        return $this->partage;
    }

    public function setPartage(bool $partage): self
    {
        $this->partage = $partage;

        return $this;
    }
}

src/Entity/Users.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UsersRepository")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class Users implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $username;

    /**
     * @ORM\Column(type="date")
     */
    private $birthdate;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="date")
     */
    private $created_at;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Lists", mappedBy="author_id")
     */
    private $lists;

    /**
     * CONSTRUCTEUR
     **/
    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->roles = ['ROLE_USER'];
        $this->lists = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        //$roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getBirthdate(): ?\DateTimeInterface
    {
        return $this->birthdate;
    }

    public function setBirthdate(\DateTimeInterface $birthdate): self
    {
        $this->birthdate = $birthdate;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection|Lists[]
     */
    public function getLists(): Collection
    {
        return $this->lists;
    }

    public function addList(Lists $list): self
    {
        if (!$this->lists->contains($list)) {
            $this->lists[] = $list;
            $list->setAuthorId($this);
        }

        return $this;
    }

    public function removeList(Lists $list): self
    {
        if ($this->lists->contains($list)) {
            $this->lists->removeElement($list);
            // set the owning side to null (unless already changed)
            if ($list->getAuthorId() === $this) {
                $list->setAuthorId(null);
            }
        }

        return $this;
    }
}

src/Controller/ProfileController.php
<?php

namespace App\Controller;

use App\Entity\Users;
use App\Form\UsersType;
use App\Repository\ListsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

/**
 * @Route("/profile")
 */
class ProfileController extends AbstractController
{


    /**
     * @Route("/{id}", name="profile_show", methods={"GET"})
     */
    public function show(Users $user): Response
    {
        return $this->render('profile/show.html.twig', [
            'user' => $user,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="profile_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Users $user, UserPasswordEncoderInterface $passwordEncoder): Response
    {
        $form = $this->createForm(UsersType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user->setPassword(
                $passwordEncoder->encodePassword(
                    $user,
                    $form->get('plainPassword')->getData()
                )
            );
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('profile_show', [
                'id' => $user->getId(),
            ]);
        }

        return $this->render('profile/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="profile_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Users $user): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($user);
            $entityManager->flush();
        }

        $this->get('security.token_storage')->setToken(null);
        $request->getSession()->invalidate();

        return $this->redirectToRoute('home');
    }

    /**
     * @Route("/{id}/lists", name="user_lists", methods={"GET"})
     */

    public function showList(Users $user, ListsRepository $listsRepository): Response
    {
        return $this->render('profile/show_lists.html.twig', [
            'lists' => $listsRepository->findBy([
                'author_id' => $user->getId(),
            ])
        ]);

    }
}

templates/profile/_delete_form.html.twig
<form method="post" action="{{ path('profile_delete', {'id': user.id}) }}"
      onsubmit="return confirm('Etes-vous sûr de vouloir effacer cet utilisateur ?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn btn-danger">Supprimer votre compte</button>
</form>

templates/profile/_form.html.twig
{{ form_start(form) }}
        {{ form_errors(form) }}
<div class="mt-3">
    {{ form_label(form.username, 'Pseudo') }}
    {{ form_errors(form.username) }}
    {{ form_widget(form.username) }}
    {{ form_help(form.username) }}
</div>
<div class="mt-3">{{ form_row(form.plainPassword) }}</div>
<div class="mt-3">
    {{ form_label(form.birthdate, 'Date de naissance') }}
    {{ form_errors(form.birthdate) }}
    {{ form_widget(form.birthdate) }}
    {{ form_help(form.birthdate) }}
</div>
<div class="mt-3">{{ form_row(form.description) }}</div>

<div class="d-flex justify-content-between mb-3">
<button class="btn btn-secondary">Enregistrer</button>

{{ form_end(form) }}

templates/profile/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edition de l'utilisateur{% endblock %}

{% block body %}
    <div class="container w-50 border mt-3">
    <h1>Edition de l'utilisateur</h1>

    {{ include('profile/_form.html.twig', {'button_label': 'Update'}) }}

        <a class="btn btn-dark ml-5" href="{{ path('profile_show', {'id': app.user.id}) }}">Retour au profil</a>

    {{ include('profile/_delete_form.html.twig') }}
        </div>
    </div>
{% endblock %}

templates/profile/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Utilisateur{% endblock %}

{% block body %}
    <div class="container w-50 mt-3 border col">
        <h1>Profil de {{ user.username }}</h1>

        <table class="table mt-3 row">
            <tbody>
            <tr>
                <th style="width:200px;">Utilisateur n° : </th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>Email : </th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>Rôles : </th>
                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>Pseudo : </th>
                <td>{{ user.username }}</td>
            </tr>
            <tr>
                <th>Date de naissance : </th>
                <td>{{ user.birthdate ? user.birthdate|date('d-m-Y') : '' }}</td>
            </tr>
            <tr>
                <th>Description : </th>
                <td>{{ user.description }}</td>
            </tr>
            <tr>
                <th>Créé le : </th>
                <td>{{ user.createdAt ? user.createdAt|date('d-m-Y') : '' }}</td>
            </tr>
            </tbody>
        </table>

        <div class="d-flex justify-content-between mb-3">
            <a class="btn btn-secondary" href="{{ path('profile_edit', {'id': user.id}) }}">Edition</a>

            {{ include('profile/_delete_form.html.twig') }}
        </div>
    </div>
{% endblock %}

templates/profile/show_lists.html.twig
{% extends 'base.html.twig' %}

{% block title %}Listes personnalisées{% endblock %}

{% block body %}
<div class="container mt-2">
    <h1 class="mb-4">Listes personnalisées</h1>

    <table class="table table-striped">
        <thead class="thead-dark">
        <tr>
            <th>Id</th>
            <th>Nom</th>
            <th>Description</th>
            <th>Auteur</th>
            <th>Partagée</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for list in lists %}
            <tr>
                <td>{{ list.id }}</td>
                <td>{{ list.name }}</td>
                <td>{{ list.description }}</td>
                <td>{{ list.authorId.username }}</td>
                <td>{{ list.partage ? 'Oui' : 'Non' }}</td>
                <td class="d-inline-block d-flex">
                    <a class="btn btn-dark mr-2" href="{{ path('lists_show', {'id': list.id}) }}">Voir</a>
                    <a class="btn btn-dark" href="{{ path('lists_edit', {'id': list.id}) }}">Editer</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">Aucune liste personnalisée</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>


    <a class="btn btn-dark" href="{{ path('lists_new') }}">Nouvelle liste</a>
    {% endblock %}